project_fix/project_fix/urls.py
from django.contrib import admin
from . import views
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home ),
    path('about/', views.about, name='about' ),
    path('showmedia/', include('showmedia.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project_fix/showmedia/urls.py
from django.urls import path
from . import views

app_name = 'showmedia'

urlpatterns = [
    path('photos/', views.photos_view, name='photos')
]

project_fix/showmedia/models.py
from django.db import models

# Create your models here.
from django.db import models

class Photo(models.Model):
    name = models.CharField(max_length=100)
    image = models.ImageField(upload_to='photos/')

project_fix/project_fix/views.py
from django.shortcuts import render


def home(request):
    return render(request, 'main/home.html')



def about(request):
    context = {
        "name": "Mohapi home you are doing owk ",
        "Viper": "Tuwane Mohapi",
        "Code": 224
    }
    return render(request, 'main/about.html', context)

project_fix/showmedia/views.py
from django.shortcuts import render

# Create your views here.

def photos_view(request):
    return render(request, 'show/photos.html')

project_fix/showmedia/templates/show/photos.html
{% extends "main/base.html" %}
{% load static %}
{% block title %}
Images
{% endblock %}



{% block content %}
<h1>Images</h1>
<h3>Wellcome to images</h3>

<img src="{% static 'images/pic2.png' %}" alt="pic2">


{% endblock %}

project_fix/templates/main/about.html
{% extends "main/base.html" %}
{% load static %}

{% block title %}
    about
{% endblock %}



{% block content %}
<h1>About</h1>
<p><a href="/">Home</p></a>
<p>Hello {{name}}</p>
<p>BSS {{Viper}}</p>
<p>Code {{Code}}</p>

{% endblock %}

project_fix/templates/main/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>
        {% block title %}
            My site
        {% endblock title %}
    </title>
</head>
<body>

    <nav>
        <a href="/">Home</a> |

        <a href="/about">About</a> |

        <a href="{% url 'showmedia:photos' %}">Photos</a> |
        <a href="#">#</a> |
        <a href="#">#</a> |

        
     </nav>

{% block content %}

{% endblock  %}
    
</body>
</html>

project_fix/templates/main/home.html
{% extends "main/base.html" %}
{% load static %}

{% block title %}
Home
{% endblock %}



{% block content %}
<h1>Home</h1>
<h3>Wellcome home</h3>
{% endblock %}

templates/main/about.html
{% extends "main/base.html" %}

{% block title %}
    about
{% endblock %}



{% block content %}
<h1>About</h1>
<p><a href="/">Home</p></a>
{% endblock %}

templates/main/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>
        {% block title %}
            
        {% endblock title %}
    </title>
</head>
<body>

    <nav>
        <a href="/">Home</a> |

        <a href="/about">About</a> |

        <a href="{% url 'loginV:login' %}">Login</a> |
        <a href="{% url 'loginV:register' %}">Register</a> |
        <a href="{% url 'loginV:logout' %}">Logout</a> |

        
     </nav>

{% block content %}

{% endblock  %}
    
</body>
</html>

templates/main/home.html
{% extends "main/base.html" %}

{% block title %}
Home
{% endblock %}



{% block content %}
<h1>Home</h1>

{% endblock %}